import { createElement } from 'lwc';
import AmplitudeAgAppAccountRedusereFravaer from 'c/amplitudeAgAppAccountRedusereFravaer';

describe('c-amplitude-ag-app-account-redusere-fravaer', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-amplitude-ag-app-account-redusere-fravaer', {
            is: AmplitudeAgAppAccountRedusereFravaer
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});